version: '3'

services:
  ccs:
    image: jhaeger/ccs-calendarserver:latest
    restart: always
    environment:
      - POSTGRES_HOST=tcp:db:5432
      - POSTGRES_DB=${DB_NAME:-ccs}
      - POSTGRES_USER=${DB_USER:-caldavd}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Please provide a database password!}
      - MEMCACHED_HOST=cache
      - MEMCACHED_PORT=11211
      - VIRTUAL_PORT=8008
      - VIRTUAL_HOST=${CCS_HOSTNAME:?Please provide a hostname for nginx proxy!}
    volumes:
     - ccs_data:/var/db/caldavd
     - ${CCS_CONFIG_PATH:?Please provide the path to the config files!}:/etc/caldavd
    networks:
      - ccs-internal
      - web-proxy
    depends_on:
      - db
      - cache

  db:
    image: postgres:9-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-ccs}
      - POSTGRES_USER=${DB_USER:-caldavd}
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ${CCS_DB_INIT_PATH:?Please provide the path to current.sql!}:/docker-entrypoint-initdb.d/ccs.sql
      - ccs_db:/var/lib/postgresql/data
    networks:
      - ccs-internal

  cache:
    image: memcached:1.6-alpine
    restart: always
    networks:
      - ccs-internal

  backup:
    image: jhaeger/postgres-backup:1.0.1
    restart: always
    environment:
      - CRON_TIMER=${BACKUP_CRON_TIMER:-0 0 * * *}
      - TZ=${BACKUP_CRON_TZ:-Etc/UTC}
      - BACKUP_DB_HOST=db
      - BACKUP_DB=${DB_NAME:-ccs}
      - BACKUP_DB_USER=${DB_USER:-caldavd}
      - BACKUP_DB_PASSWORD=$DB_PASSWORD
    volumes:
      - ccs_backups:/root/backups
    networks:
      - ccs-internal
    depends_on:
      - db

networks:
  ccs-internal:
    internal: true
  web-proxy:
    external: true

volumes:
  ccs_db:
  ccs_data:
  ccs_backups:
